### PR TITLE
Add standardized copyright headers.

### PR DESCRIPTION
**Pull request by waywardmonkeys**

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
This is preparation for adding Linebender CI.

**Comment by waywardmonkeys** [comment]
@DJMcNab @xStrom You might want to bike shed the usage of "the svgtypes Authors". Let me know exactly what to change it to if you want it changed.

**Comment by DJMcNab** [comment]
I think this is also the time to add the AUTHORS file.

**Comment by waywardmonkeys** [comment]
@DJMcNab Done.

**Comment by xStrom** [comment]
> You might want to bike shed the usage of "the svgtypes Authors". Let me know exactly what to change it to if you want it changed.

Started some discussion on it [in Zulip](https://xi.zulipchat.com/#narrow/channel/465085-resvg/topic/Name.20capitalization).

**Comment by waywardmonkeys** [comment]
Updated per decision in Zulip.

**Review by DJMcNab — APPROVED** [review]
I've not validated the dates, but I believe the dates don't hold any significance

**Pull request merged**
